### ISSUE TITLE
Definição do Banco de Dados

### ISSUE THREAD

**Issue by Stefano10** [Processos-de-software-2016-2/python-api#1]
Definição do Banco de Dados juntamente com o team de Infraestrutura.

**Comment by joaomedeiros95** [comment]
Na minha opinião devemos escolher o SGBD MySQL já que o sistema que estamos implantando é simples e não demanda muitos recursos que são exclusivos do PostgresSQL, como o MySQL é mais simples e, possivelmente, um pouco mais rápido acho que devemos ficar com ele.

**Comment by joaomedeiros95** [comment]
Banco de dados a ser usado **MySQL**
