### ISSUE TITLE
Definição do Framework Python para criação de API

### ISSUE THREAD

**Issue by Stefano10** [Processos-de-software-2016-2/python-api#2]
Possíveis opções: 
Flask - Stefano
Botton - Vinicius
Falcon - Victor

**Comment by joaomedeiros95** [comment]
https://falconframework.org/
http://flask.pocoo.org/
https://bottlepy.org/docs/dev/

**Comment by victorsv** [comment]
Dei uma olhada sobre o Falcon framework.

Por cima, ele parece ser bem simples de usar, especialmente para a criação dos get/post/delete/outros. E o benchmarking dele é bem promissor. Com o PyPy, ele até 45 vezes mais rápido/eficiente em casos ideais do que os outros frameworks que estamos considerando, no caso do Flask.

Por outro lado, eu também dei uma olhada sobre o Flask, só que foi bem mais superficial. Comparado com ele, of Falcon é bem especializado em APIs, e não é um conjunto "completo" de desenvolvimento como o Ruby on Rails ou o Laravel. Se isso é bom ou ruim, eu não sei comentar, já que desenvolvimento web é uma área que só comecei a me aproximar recentemente.

**Comment by Stefano10** [comment]
Sobre flask: 

Pelo que li, ele é mais flexível e faz bem mais coisas. Temos que comparar também o quesito de autenticação e boa documentação.

Link de tutoriais: http://blog.luisrei.com/articles/flaskrest.html
http://flask.pocoo.org/

**Comment by joaomedeiros95** [comment]
Framework definido **Falcon**
